# Generated by Django 5.0.6 on 2024-06-13 12:06

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, BtreeGinExtension

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
        BtreeGinExtension(),
    ]
