# Generated by Django 5.0.6 on 2024-06-14 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_Add_Keywords_Field'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Volgorde'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Aantal'),
        ),
    ]
