# Generated by Django 5.0.6 on 2024-06-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_Add_Uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
